# Text Representation techniques

### Bag Of Words

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.DataFrame({'Text':['Prachi writes code','Code writes code','Prachi reads book','Code reads book'], 'Output':[1,1,0,0]})

In [ ]:
df

,Text,Output
0,Prachi writes code,1
1,Code writes code,1
2,Prachi reads book,0
3,Code reads book,0


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['Text'])

In [ ]:
# the numbers given beside the word is index

print(cv.vocabulary_)

{'prachi': 2, 'writes': 4, 'code': 1, 'reads': 3, 'book': 0}


In [ ]:
# Converting first sentence into vector

print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 1]]
[[0 2 0 0 1]]


### N-Grams

##### In N-grams if n=(2,2), it will create the pair of 2 words from the corpus sequentially and if (1,2) then it will add both single words and the pair of 2 words into the vocabulary

In [ ]:
cv1 = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow1 = cv1.fit_transform(df['Text'])

In [ ]:
print(cv1.vocabulary_)

{'prachi writes': 3, 'writes code': 5, 'code writes': 1, 'prachi reads': 2, 'reads book': 4, 'code reads': 0}


In [ ]:
print(bow1[0].toarray())

[[0 0 0 1 0 1]]


### Tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit_transform(df['Text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.        , 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.        , 0.61366674, 0.        ]])

In [ ]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


##### Tf : term frequesncy
 IDF : Inverse document frequecy

- Tf is calculated by dividing frequency of that term in documents by total number of terms in document
- IDf is calculated by taking the log of diving total no. of documents in the corpus by no. of documents containing that term

# Word2Vec


In [ ]:
# Word embedding : In natural language processing, word embedding is a term used for the
#                  representation of words for text analysis, typically in the form of a real-valued
#                  vector that encodes the meaning of the word such that the words that are closer
#                  in the vector space are expected to be similar in meaning.

# Two types of word embedding: 1. Frequency based (ex. Tf-idf, BOW)
#                              2. Prediction (ex. Word2Vec)

In [ ]:

!pip install gensim
import gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 48.6 MB/s eta 0:00:00


In [ ]:
from gensim.models import Word2Vec, keyedvectors

In [ ]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=d0d504dfe87ba794b92eae08f1db77b6c506e4511bcc706837bf3987e9ae002b
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget


In [ ]:
import gensim.downloader as api

# You can list available models using api.info()
# For example, to load Google's pre-trained Word2Vec model:
# wv = api.load('word2vec-google-news-300')

print("To load the Word2Vec Google News model, you can use: wv = api.load('word2vec-google-news-300')")
print("Note: This download might take some time as the file is large.")

To load the Word2Vec Google News model, you can use: wv = api.load('word2vec-google-news-300')
Note: This download might take some time as the file is large.


In [ ]:
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
model = wv

In [ ]:
model['man'].shape

(300,)

In [ ]:
model['bottle']

array([-0.02941895,  0.11767578, -0.15039062,  0.00192261, -0.11230469,
        0.30273438,  0.38476562, -0.2734375 ,  0.23828125,  0.29492188,
       -0.08056641, -0.48242188,  0.05664062, -0.01623535, -0.31054688,
        0.14941406, -0.16308594,  0.26757812,  0.09521484, -0.109375  ,
        0.24414062,  0.09228516, -0.02404785, -0.15136719, -0.13769531,
        0.18066406,  0.02270508,  0.26171875,  0.11230469,  0.12695312,
        0.12060547, -0.00159454, -0.24511719,  0.04833984, -0.08935547,
        0.00787354,  0.14257812, -0.04736328, -0.15039062, -0.00081253,
       -0.33984375,  0.109375  ,  0.34570312, -0.11669922,  0.10253906,
       -0.15234375, -0.02868652,  0.07324219,  0.11669922, -0.25390625,
       -0.38867188, -0.10693359,  0.02441406, -0.31054688,  0.0534668 ,
       -0.07275391,  0.14453125,  0.15332031, -0.06225586, -0.07177734,
       -0.27929688,  0.05224609,  0.13964844, -0.02282715, -0.08642578,
       -0.11572266,  0.05932617, -0.3359375 ,  0.34179688, -0.03

In [ ]:
model.most_similar('girl')

[('boy', 0.8543271422386169),
 ('teenage_girl', 0.7927975654602051),
 ('woman', 0.7494640946388245),
 ('teenager', 0.7172499299049377),
 ('schoolgirl', 0.7075953483581543),
 ('teenaged_girl', 0.6650916337966919),
 ('daughter', 0.6489864587783813),
 ('mother', 0.6478164196014404),
 ('toddler', 0.6473966836929321),
 ('girls', 0.6154742240905762)]

In [ ]:
model.most_similar('laptop')

[('laptops', 0.8053741455078125),
 ('laptop_computer', 0.7848465442657471),
 ('notebook', 0.67857825756073),
 ('netbook', 0.6707928776741028),
 ('computer', 0.6640493273735046),
 ('laptop_computers', 0.6633791327476501),
 ('notebook_PC', 0.6631842851638794),
 ('MacBook', 0.6598750352859497),
 ('PowerBook', 0.6520565748214722),
 ('Sony_Vaio_laptop', 0.6496157050132751)]

In [ ]:
model.most_similar('makeup')

[('Makeup', 0.623534619808197),
 ('eyeliner', 0.5594107508659363),
 ('makeups', 0.5380759835243225),
 ('haircolor', 0.5291092991828918),
 ('airbrush_makeup', 0.5236254930496216),
 ('Makeup.com_Limited', 0.5140296220779419),
 ('bronzer', 0.5137912631034851),
 ('lip_gloss', 0.5124861001968384),
 ('makeup_artist', 0.5094521641731262),
 ('Greg_Cannom', 0.5085016489028931)]

In [ ]:
model.most_similar('bike')

[('bicycle', 0.8521308898925781),
 ('bikes', 0.8127913475036621),
 ('mountain_bike', 0.7518467307090759),
 ('scooter', 0.749575674533844),
 ('motorcycle', 0.7016158699989319),
 ('Bike', 0.7006312012672424),
 ('biking', 0.679279625415802),
 ('BMX_bike', 0.6724931597709656),
 ('bicycles', 0.670872688293457),
 ('moped', 0.6429066061973572)]

In [ ]:
model.similarity('monkey','gorilla')

np.float32(0.6353992)

In [ ]:
model.similarity('you','me')

np.float32(0.56798255)

In [ ]:
model.doesnt_match(['king','crown','me'])

'me'

In [ ]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [ ]:
# The underlying assumption of Word2Vec is that two words sharing similar contexts
# also share a similar meaning and consequently a similar vector representation
# from the model.

## Two types of Word2vec

- CBOW (Continuous bag of words): Given context word predict target word

- Skip-grams: Given target word predict context word

#### - if working with small data use CBOW (fast & accurate for small)
#### - if large data then go with skip-gram

In [ ]:
# if you want to increase the quality of w2v:
# 1. increase training data
# 2. increase dimentions of vector
# 3. increase window size